version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: semver
    versions:
    - 7.3.4
  - dependency-name: style-loader
    versions:
    - 1.2.1
  - dependency-name: express-validator
    versions:
    - 6.9.2
